# Generated by Django 5.0.6 on 2024-09-18 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tes_app', '0003_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='mode',
            field=models.CharField(choices=[('Unblock', 'Unblock'), ('Block', 'Block')], default='Unblock', max_length=12),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FRIEND_REQUEST_SENT', 'Friend Request Sent'), ('FRIEND_REQUEST_ACCEPTED', 'Friend Request Accepted'), ('FRIEND_REQUEST_REJECTED', 'Friend Request Rejected'), ('FRIEND_REQUEST_BLOCKED', 'Friend Request Blocked'), ('FRIEND_REQUEST_UNBLOCKED', 'Friend Request Unblocked')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logged_activities', to='tes_app.friendrequest')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
